In [ ]:
import numpy as np

In [ ]:
a=np.array([[[1,2],[3,4]],
            [[5,6],[7,8]],
            [[0,1],[2,3]]])

In [ ]:
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[0, 1],
        [2, 3]]])

In [ ]:
a.sum(axis=2)

array([[ 3,  7],
       [11, 15],
       [ 1,  5]])

array([[[False, False],
        [False,  True]],

       [[ True,  True],
        [ True,  True]],

       [[False, False],
        [False, False]]])

In [ ]:
a.sum(axis=1)

array([3, 7])

# Pandas

Pandas is a package used for managing data.

Pandas main use is that it creates 2 new data types for storing data: series and dataframe.

A dataframe is made up of several series.  Each column of a dataframe is a series.

We can name each column and row of a dataframe.

Similar to numpy arrays, a dataframe is a more robust data type for storing data than lists of lists. Dataframes are more flexible than numpy arrays.

A numpy array can create a matrix with all entries of the same data type.  In a dataframe each column can have its own datatype.  

That's not to say numpy arrays aren't useful.  It is often easiest to convert some subset of a dataframe to a numpy array and then use that to do some math.

Pandas also has SQL-like functions for merging, joining, and sorting dataframes.



In [ ]:
!pip install pandas

In [ ]:
import pandas as pd
import numpy as np  # numpy is not necessary for pandas, but we will use some np code in this example
# in general it's good practice to import all pacakages at the beginning

In [ ]:
series - list, np.array

In [ ]:
mylist=[1,2,3,4]
array=np.random.randint(10,20,4) 

In [ ]:
array

array([11, 15, 12, 14])

In [ ]:
s1=pd.Series(mylist)
s1

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
s2=pd.Series(array)
s2

0    11
1    15
2    12
3    14
dtype: int32

In [ ]:
# first let's look at series - think of this as a single column of a spreadsheet
# each entry in a series corresponds to an individual row in the spreadsheet
# we can create a series by converting a list, or numpy array

mylist = [5.4,6.1,1.7,99.8]
myarray = np.array(mylist)


In [ ]:
a=pd.Series(mylist)
a

0     5.4
1     6.1
2     1.7
3    99.8
dtype: float64

In [ ]:
myseries1 = pd.Series(data=mylist)
print(myseries1)
myseries2 = pd.Series(data=myarray)
print(myseries2)

0     5.4
1     6.1
2     1.7
3    99.8
dtype: float64
0     5.4
1     6.1
2     1.7
3    99.8
dtype: float64


In [ ]:
# we access individual entries the same way as with lists and arrays
print(myseries2[2:])

2     1.7
3    99.8
dtype: float64


In [ ]:
# we can add labels to the entries of a series

mylabels = ['first','second','third','fourth']
myseries3 = pd.Series(data=mylist,index=mylabels)
print(myseries3)

first      5.4
second     6.1
third      1.7
fourth    99.8
dtype: float64


In [ ]:
# we need not be explicit about the entries of pd.Series
myseries4 = pd.Series(mylabels,mylist)
print(myseries4)

5.4      first
6.1     second
1.7      third
99.8    fourth
dtype: object


In [ ]:
# we can also access entries using the index labels
print(myseries3['fourth'])

99.8


In [ ]:
myseries4[5.4]

'first'

In [ ]:
# myseries5

In [ ]:
# we can do math on series 
myseries5 = pd.Series([5.5,1.1,8.8,1.6],['first','third','fourth','fifth'])
print(myseries5)
print('')
print(myseries5+myseries3)

first     5.5
third     1.1
fourth    8.8
fifth     1.6
dtype: float64

fifth       NaN
first      10.9
fourth    108.6
second      NaN
third       2.8
dtype: float64


In [ ]:
concatenate 1,2 - 12

In [ ]:
print(myseries3)
print()
print(myseries5)

first      5.4
second     6.1
third      1.7
fourth    99.8
dtype: float64

first     5.5
third     1.1
fourth    8.8
fifth     1.6
dtype: float64


In [ ]:
# we can combine series to create a dataframe using the concat function

df1 = pd.concat([myseries3,myseries5],axis=1,sort=False)
df1

0    1
first    5.4  5.5
second   6.1  NaN
third    1.7  1.1
fourth  99.8  8.8
fifth    NaN  1.6

In [ ]:
# we can create a new dataframe 
df2 = pd.DataFrame(np.random.rand(5,5),index=['a','b','c','d','e'],columns=['p','q','r','s','t'])
df2

p         q         r         s         t
a  0.482268  0.112784  0.639393  0.664639  0.917334
b  0.396474  0.372235  0.294564  0.024484  0.710847
c  0.544272  0.067242  0.458721  0.696116  0.599218
d  0.407176  0.832049  0.431591  0.516257  0.874876
e  0.809323  0.106928  0.695921  0.143821  0.693984

In [ ]:
# lets give labels to rows and columns
df3 = pd.DataFrame(np.random.randn(5,5),index=['first row','second row','third row','fourth row','fifth row'],
                   columns=['first col','second col','third col','fourth col','fifth col'])
df3

first col  second col  third col  fourth col  fifth col
first row   -0.248954   -2.090749   0.766858   -0.838886   0.633128
second row  -1.022491   -0.284207  -0.037904   -1.794641   0.859787
third row    2.305055    0.990373  -1.062569   -0.393941  -0.518357
fourth row  -1.620665   -0.894481  -2.206637    1.889650  -0.168061
fifth row   -0.793989    0.815225   0.244170   -1.834688   0.020800

In [ ]:
df3[['third col','fourth col','first col']]

third col  fourth col  first col
first row    0.766858   -0.838886  -0.248954
second row  -0.037904   -1.794641  -1.022491
third row   -1.062569   -0.393941   2.305055
fourth row  -2.206637    1.889650  -1.620665
fifth row    0.244170   -1.834688  -0.793989

In [ ]:
df3.columns

Index(['first col', 'second col', 'third col', 'fourth col', 'fifth col'], dtype='object')

In [ ]:
df3.loc[['second row','fourth row'],['third col','first col']]

third col  first col
second row  -0.037904  -1.022491
fourth row  -2.206637  -1.620665

In [ ]:
df3

first col  second col  third col  fourth col  fifth col
first row   -0.248954   -2.090749   0.766858   -0.838886   0.633128
second row  -1.022491   -0.284207  -0.037904   -1.794641   0.859787
third row    2.305055    0.990373  -1.062569   -0.393941  -0.518357
fourth row  -1.620665   -0.894481  -2.206637    1.889650  -0.168061
fifth row   -0.793989    0.815225   0.244170   -1.834688   0.020800

In [ ]:
df3.iloc[1:4,3:]

fourth col  fifth col
second row   -1.794641   0.859787
third row    -0.393941  -0.518357
fourth row    1.889650  -0.168061

In [ ]:
# we can access individual series in a data frame
print(df3['second col'])
print('')
df3[['third col','first col']]

first row     0.392322
second row   -0.545976
third row     0.154637
fourth row    1.347788
fifth row    -1.656737
Name: second col, dtype: float64



third col  first col
first row   -0.124973  -0.997329
second row   0.179702   0.016515
third row    0.383640  -0.397730
fourth row  -1.010151  -0.123778
fifth row   -1.381358  -0.034453

In [ ]:
# we can access rows of a dataframe
df3.loc['fourth row']

first col    -0.123778
second col    1.347788
third col    -1.010151
fourth col   -0.487149
fifth col     0.724082
Name: fourth row, dtype: float64

In [ ]:
df3.loc[['fourth row','third row'],['second col','first col']]

second col  first col
fourth row    1.347788  -0.123778
third row     0.154637  -0.397730

In [ ]:
df3.iloc[2:,3:]

fourth col  fifth col
third row    -0.023996   0.526021
fourth row   -0.487149   0.724082
fifth row    -1.181719  -0.319324

In [ ]:
df3

first col  second col  third col  fourth col  fifth col
first row   -0.997329    0.392322  -0.124973   -0.730586  -0.989552
second row   0.016515   -0.545976   0.179702    0.911808  -0.505986
third row   -0.397730    0.154637   0.383640   -0.023996   0.526021
fourth row  -0.123778    1.347788  -1.010151   -0.487149   0.724082
fifth row   -0.034453   -1.656737  -1.381358   -1.181719  -0.319324

In [ ]:
df3[df3.iloc[:,:2]>0]

first col  second col  third col  fourth col  fifth col
first row         NaN    0.392322        NaN         NaN        NaN
second row   0.016515         NaN        NaN         NaN        NaN
third row         NaN    0.154637        NaN         NaN        NaN
fourth row        NaN    1.347788        NaN         NaN        NaN
fifth row         NaN         NaN        NaN         NaN        NaN

In [ ]:
df3.iloc[4:,2:]

third col  fourth col  fifth col
fifth row  -1.381358   -1.181719  -0.319324

In [ ]:
df3.loc[['fourth row','first row'],['second col','third col']]

second col  third col
fourth row    1.347788  -1.010151
first row     0.392322  -0.124973

In [ ]:
df3

first col  second col  third col  fourth col  fifth col
first row   -0.248954   -2.090749   0.766858   -0.838886   0.633128
second row  -1.022491   -0.284207  -0.037904   -1.794641   0.859787
third row    2.305055    0.990373  -1.062569   -0.393941  -0.518357
fourth row  -1.620665   -0.894481  -2.206637    1.889650  -0.168061
fifth row   -0.793989    0.815225   0.244170   -1.834688   0.020800

In [ ]:
# we can use logical indexing for dataframes just like for numpy arrays
df3>0

first col  second col  third col  fourth col  fifth col
first row       False       False       True       False       True
second row      False       False      False       False       True
third row        True        True      False       False      False
fourth row      False       False      False        True      False
fifth row       False        True       True       False       True

In [ ]:
df3[(df3>0)]

first col  second col  third col  fourth col  fifth col
first row         NaN    0.392322        NaN         NaN        NaN
second row   0.016515         NaN   0.179702    0.911808        NaN
third row         NaN    0.154637   0.383640         NaN   0.526021
fourth row        NaN    1.347788        NaN         NaN   0.724082
fifth row         NaN         NaN        NaN         NaN        NaN

In [ ]:
# df3['sixth col']=['This','is','a','new','col']
df3['abc']=['Yet','another','new','col',np.NaN]
df3

first col  second col  third col  fourth col  fifth col sixth col  \
first row   -0.248954   -2.090749   0.766858   -0.838886   0.633128      This   
second row  -1.022491   -0.284207  -0.037904   -1.794641   0.859787        is   
third row    2.305055    0.990373  -1.062569   -0.393941  -0.518357         a   
fourth row  -1.620665   -0.894481  -2.206637    1.889650  -0.168061       new   
fifth row   -0.793989    0.815225   0.244170   -1.834688   0.020800       col   

                abc  
first row       Yet  
second row  another  
third row       new  
fourth row      col  
fifth row       NaN

In [ ]:
# we can add columns to a dataframe
df3['sixth col'] = np.random.randn(5,1)
df3

first col  second col  third col  fourth col  fifth col  \
first row   -0.248954   -2.090749   0.766858   -0.838886   0.633128   
second row  -1.022491   -0.284207  -0.037904   -1.794641   0.859787   
third row    2.305055    0.990373  -1.062569   -0.393941  -0.518357   
fourth row  -1.620665   -0.894481  -2.206637    1.889650  -0.168061   
fifth row   -0.793989    0.815225   0.244170   -1.834688   0.020800   

            sixth col      abc  
first row   -1.164861      Yet  
second row  -0.834197  another  
third row    1.053753      new  
fourth row  -1.533005      col  
fifth row    0.778935      NaN

In [ ]:
# we can remove columns or rows from a dataframe
# Method 1
df3=df3.drop('third col',axis=1)

In [ ]:
# Method 2
df3.drop('abc',axis=1,inplace=True)

In [ ]:
df3

second col  fourth col  fifth col  sixth col
first row    -2.090749   -0.838886   0.633128  -1.164861
second row   -0.284207   -1.794641   0.859787  -0.834197
third row     0.990373   -0.393941  -0.518357   1.053753
fourth row   -0.894481    1.889650  -0.168061  -1.533005
fifth row     0.815225   -1.834688   0.020800   0.778935

In [ ]:
df3.drop('second col',axis=1)

third col  fourth col  fifth col  sixth col
first row   -0.124973   -0.730586  -0.989552   0.859396
second row   0.179702    0.911808  -0.505986  -0.101485
third row    0.383640   -0.023996   0.526021   0.379618
fourth row  -1.010151   -0.487149   0.724082   2.302619
fifth row   -1.381358   -1.181719  -0.319324   0.745309

In [ ]:
df3

second col  third col  fourth col  fifth col  sixth col
first row     0.392322  -0.124973   -0.730586  -0.989552   0.859396
second row   -0.545976   0.179702    0.911808  -0.505986  -0.101485
third row     0.154637   0.383640   -0.023996   0.526021   0.379618
fourth row    1.347788  -1.010151   -0.487149   0.724082   2.302619
fifth row    -1.656737  -1.381358   -1.181719  -0.319324   0.745309

In [ ]:
df4 = df3.drop(['second col'],axis=1)
df4

third col  fourth col  fifth col  sixth col
first row   -0.124973   -0.730586  -0.989552   0.859396
second row   0.179702    0.911808  -0.505986  -0.101485
third row    0.383640   -0.023996   0.526021   0.379618
fourth row  -1.010151   -0.487149   0.724082   2.302619
fifth row   -1.381358   -1.181719  -0.319324   0.745309

In [ ]:
df5 = df3.drop('second row',axis=0)
df5

second col  fourth col  fifth col  sixth col
first row    -2.090749   -0.838886   0.633128  -1.164861
third row     0.990373   -0.393941  -0.518357   1.053753
fourth row   -0.894481    1.889650  -0.168061  -1.533005
fifth row     0.815225   -1.834688   0.020800   0.778935

In [ ]:
df3=df3.drop('second row',axis=0)
df3

second col  fourth col  fifth col  sixth col
first row    -2.090749   -0.838886   0.633128  -1.164861
third row     0.990373   -0.393941  -0.518357   1.053753
fourth row   -0.894481    1.889650  -0.168061  -1.533005
fifth row     0.815225   -1.834688   0.020800   0.778935

In [ ]:
df3.drop('fifth row',axis=0,inplace=True)
df3

second col  fourth col  fifth col  sixth col
first row    -2.090749   -0.838886   0.633128  -1.164861
third row     0.990373   -0.393941  -0.518357   1.053753
fourth row   -0.894481    1.889650  -0.168061  -1.533005