In [ ]:
import numpy as np

In [ ]:
a=np.array([[[1,2],[3,4]],
            [[5,6],[7,8]],
            [[0,1],[2,3]]])

In [ ]:
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[0, 1],
        [2, 3]]])

In [ ]:
a.sum(axis=0)

array([[ 6,  9],
       [12, 15]])

In [ ]:
a.sum(axis=1)

array([[ 4,  6],
       [12, 14],
       [ 2,  4]])

In [ ]:
a.sum(axis=2)

array([[ 3,  7],
       [11, 15],
       [ 1,  5]])

# Pandas

Pandas is a package used for managing data.

Pandas main use is that it creates 2 new data types for storing data: series and dataframe.

A dataframe is made up of several series.  Each column of a dataframe is a series.

We can name each column and row of a dataframe.

Similar to numpy arrays, a dataframe is a more robust data type for storing data than lists of lists. Dataframes are more flexible than numpy arrays.

A numpy array can create a matrix with all entries of the same data type.  In a dataframe each column can have its own datatype.  

That's not to say numpy arrays aren't useful.  It is often easiest to convert some subset of a dataframe to a numpy array and then use that to do some math.

Pandas also has SQL-like functions for merging, joining, and sorting dataframes.



In [ ]:
!pip install pandas

In [ ]:
import pandas as pd
import numpy as np  # numpy is not necessary for pandas, but we will use some np code in this example
# in general it's good practice to import all pacakages at the beginning

In [ ]:
# series - list, np.array

In [ ]:
mylist=[1,2,3,4]
array=np.random.randint(10,20,4) 

In [ ]:
type(mylist)

list

In [ ]:
array

array([14, 15, 13, 15])

In [ ]:
s1=pd.Series(mylist)
s1

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
type(s1)

pandas.core.series.Series

In [ ]:
s2=pd.Series(array)
s2

0    14
1    15
2    13
3    15
dtype: int64

In [ ]:
# first let's look at series - think of this as a single column of a spreadsheet
# each entry in a series corresponds to an individual row in the spreadsheet
# we can create a series by converting a list, or numpy array

mylist = [5.4,6.1,1.7,99.8]
myarray = np.array(mylist)


In [ ]:
a=pd.Series(mylist)
a

0     5.4
1     6.1
2     1.7
3    99.8
dtype: float64

In [ ]:
myseries1 = pd.Series(data=mylist)
print(myseries1)
myseries2 = pd.Series(data=myarray)
print(myseries2)

0     5.4
1     6.1
2     1.7
3    99.8
dtype: float64
0     5.4
1     6.1
2     1.7
3    99.8
dtype: float64


In [ ]:
['A', 'B']*5

['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'B']

In [ ]:
[np.arange(0,10)]

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])]

In [ ]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
Ravan= {'Power': list(range(0,10)), 'Weakness': ['A', 'B']*5}
Ravan= pd.DataFrame(Ravan)
Ravan

Power Weakness
0      0        A
1      1        B
2      2        A
3      3        B
4      4        A
5      5        B
6      6        A
7      7        B
8      8        A
9      9        B

In [ ]:
np.random.rand(20)

array([0.40475936, 0.26988785, 0.24122363, 0.29091069, 0.43391474,
       0.83011757, 0.65941876, 0.86490838, 0.06149355, 0.62061715,
       0.61490989, 0.41775032, 0.82051939, 0.24410247, 0.92398489,
       0.07858634, 0.90610272, 0.47272495, 0.49389831, 0.98277148])

In [ ]:
np.random.randint(0,20,20)

array([ 8,  3, 15, 11, 15,  0, 18, 14,  8, 10,  6,  1,  3, 11, 19, 15, 17,
       10, 14,  5])

In [ ]:
np.random.rand(5,5)

array([[2.57560207e-01, 8.38763581e-02, 4.06380518e-01, 7.58059082e-05,
        2.56893983e-01],
       [9.17957377e-01, 2.38280262e-01, 6.86326930e-01, 4.94193065e-01,
        9.66953909e-01],
       [5.30175544e-01, 4.56415213e-01, 1.02406826e-01, 3.95549599e-01,
        1.58517168e-01],
       [4.11504939e-01, 2.48137439e-01, 5.60865259e-01, 8.84815533e-01,
        4.38811952e-01],
       [5.18929312e-01, 3.89399828e-01, 1.42937512e-01, 2.94743939e-01,
        7.60409814e-01]])

In [ ]:
np.random.rand(3,3)

array([[0.03288872, 0.00372642, 0.35642848],
       [0.00859569, 0.32636653, 0.32992077],
       [0.91917663, 0.61918839, 0.54941592]])

In [ ]:
pd.DataFrame(np.random.rand(3,4), index=list(range(3)), columns= ('A', 'B')*2)

A         B         A         B
0  0.740355  0.024578  0.372173  0.895780
1  0.340616  0.068845  0.681949  0.831399
2  0.413146  0.999848  0.530737  0.825796

In [ ]:
# we access individual entries the same way as with lists and arrays
print(myseries2[2:])

2     1.7
3    99.8
dtype: float64


In [ ]:
# we can add labels to the entries of a series

mylabels = ['first','second','third','fourth']
myseries3 = pd.Series(data=mylist,index=mylabels)
print(myseries3)

first      5.4
second     6.1
third      1.7
fourth    99.8
dtype: float64


In [ ]:
# we need not be explicit about the entries of pd.Series
myseries4 = pd.Series(mylabels,mylist)
print(myseries4)

5.4      first
6.1     second
1.7      third
99.8    fourth
dtype: object


In [ ]:
# we can also access entries using the index labels
print(myseries3['fourth'])

99.8


In [ ]:
myseries4[5.4]

'first'

In [ ]:
# myseries5

In [ ]:
# we can do math on series 
myseries5 = pd.Series([5.5,1.1,8.8,1.6],['first','third','fourth','fifth'])
print(myseries5)
print('')
print(myseries5+myseries3)

first     5.5
third     1.1
fourth    8.8
fifth     1.6
dtype: float64

fifth       NaN
first      10.9
fourth    108.6
second      NaN
third       2.8
dtype: float64


In [ ]:
concatenate 1,2 - 12

SyntaxError: invalid syntax (733687337.py, line 1)

In [ ]:
print(myseries3)
print()
print(myseries5)

first      5.4
second     6.1
third      1.7
fourth    99.8
dtype: float64

first     5.5
third     1.1
fourth    8.8
fifth     1.6
dtype: float64


In [ ]:
# we can combine series to create a dataframe using the concat function

df1 = pd.concat([myseries3,myseries5],axis=1,sort=False)
df1

0    1
first    5.4  5.5
second   6.1  NaN
third    1.7  1.1
fourth  99.8  8.8
fifth    NaN  1.6

In [ ]:
# we can create a new dataframe 
df2 = pd.DataFrame(np.random.rand(5,5),index=['a','b','c','d','e'],columns=['p','q','r','s','t'])
df2

p         q         r         s         t
a  0.512325  0.792790  0.107013  0.545848  0.353009
b  0.853769  0.035232  0.019195  0.712925  0.966695
c  0.790443  0.564641  0.947495  0.732308  0.063018
d  0.944952  0.675020  0.658529  0.175713  0.821730
e  0.922854  0.100087  0.999255  0.726458  0.175784

In [ ]:
# lets give labels to rows and columns
df3 = pd.DataFrame(np.random.randn(5,5),index=['first row','second row','third row','fourth row','fifth row'],
                   columns=['first col','second col','third col','fourth col','fifth col'])
df3

first col  second col  third col  fourth col  fifth col
first row    0.822893   -1.423711   0.418590    0.158221  -0.463175
second row  -0.152790    0.002065   1.858880   -0.636972  -0.738839
third row   -0.193864   -1.179945   0.380241    1.376465   0.184676
fourth row   1.131401    0.407221  -2.539193    0.328429  -0.027129
fifth row   -0.790992    0.408077  -0.746851    0.895058  -0.923893

In [ ]:
df3[['third col','fourth col','first col']]

third col  fourth col  first col
first row    0.418590    0.158221   0.822893
second row   1.858880   -0.636972  -0.152790
third row    0.380241    1.376465  -0.193864
fourth row  -2.539193    0.328429   1.131401
fifth row   -0.746851    0.895058  -0.790992

In [ ]:
df3.columns

Index(['first col', 'second col', 'third col', 'fourth col', 'fifth col'], dtype='object')

In [ ]:
df3.loc[['second row','fourth row'],['third col','first col']]

third col  first col
second row   1.858880  -0.152790
fourth row  -2.539193   1.131401

In [ ]:
df3

first col  second col  third col  fourth col  fifth col
first row    0.822893   -1.423711   0.418590    0.158221  -0.463175
second row  -0.152790    0.002065   1.858880   -0.636972  -0.738839
third row   -0.193864   -1.179945   0.380241    1.376465   0.184676
fourth row   1.131401    0.407221  -2.539193    0.328429  -0.027129
fifth row   -0.790992    0.408077  -0.746851    0.895058  -0.923893

In [ ]:
df3.iloc[1:4,3:]

fourth col  fifth col
second row   -0.636972  -0.738839
third row     1.376465   0.184676
fourth row    0.328429  -0.027129

In [ ]:
# we can access individual series in a data frame
print(df3['second col'])
print('')
df3[['third col','first col']]

first row    -1.423711
second row    0.002065
third row    -1.179945
fourth row    0.407221
fifth row     0.408077
Name: second col, dtype: float64



third col  first col
first row    0.418590   0.822893
second row   1.858880  -0.152790
third row    0.380241  -0.193864
fourth row  -2.539193   1.131401
fifth row   -0.746851  -0.790992

In [ ]:
# we can access rows of a dataframe
df3.loc['fourth row']

first col     1.131401
second col    0.407221
third col    -2.539193
fourth col    0.328429
fifth col    -0.027129
Name: fourth row, dtype: float64

In [ ]:
df3.loc[['fourth row','third row'],['second col','first col']]

second col  first col
fourth row    0.407221   1.131401
third row    -1.179945  -0.193864

In [ ]:
df3.iloc[2:,3:]

fourth col  fifth col
third row     1.376465   0.184676
fourth row    0.328429  -0.027129
fifth row     0.895058  -0.923893

In [ ]:
df3

first col  second col  third col  fourth col  fifth col
first row    0.822893   -1.423711   0.418590    0.158221  -0.463175
second row  -0.152790    0.002065   1.858880   -0.636972  -0.738839
third row   -0.193864   -1.179945   0.380241    1.376465   0.184676
fourth row   1.131401    0.407221  -2.539193    0.328429  -0.027129
fifth row   -0.790992    0.408077  -0.746851    0.895058  -0.923893

In [ ]:
df3[df3.iloc[:,:2]>0]

first col  second col  third col  fourth col  fifth col
first row    0.822893         NaN        NaN         NaN        NaN
second row        NaN    0.002065        NaN         NaN        NaN
third row         NaN         NaN        NaN         NaN        NaN
fourth row   1.131401    0.407221        NaN         NaN        NaN
fifth row         NaN    0.408077        NaN         NaN        NaN

In [ ]:
df3.iloc[4:,2:]

third col  fourth col  fifth col
fifth row  -0.746851    0.895058  -0.923893

In [ ]:
df3.loc[['fourth row','first row'],['second col','third col']]

second col  third col
fourth row    0.407221  -2.539193
first row    -1.423711   0.418590

In [ ]:
df3

first col  second col  third col  fourth col  fifth col
first row    0.822893   -1.423711   0.418590    0.158221  -0.463175
second row  -0.152790    0.002065   1.858880   -0.636972  -0.738839
third row   -0.193864   -1.179945   0.380241    1.376465   0.184676
fourth row   1.131401    0.407221  -2.539193    0.328429  -0.027129
fifth row   -0.790992    0.408077  -0.746851    0.895058  -0.923893

In [ ]:
# we can use logical indexing for dataframes just like for numpy arrays
df3>0

first col  second col  third col  fourth col  fifth col
first row        True       False       True        True      False
second row      False        True       True       False      False
third row       False       False       True        True       True
fourth row       True        True      False        True      False
fifth row       False        True      False        True      False

In [ ]:
df3[(df3>0)]

first col  second col  third col  fourth col  fifth col
first row    0.822893         NaN   0.418590    0.158221        NaN
second row        NaN    0.002065   1.858880         NaN        NaN
third row         NaN         NaN   0.380241    1.376465   0.184676
fourth row   1.131401    0.407221        NaN    0.328429        NaN
fifth row         NaN    0.408077        NaN    0.895058        NaN

In [ ]:
# df3['sixth col']=['This','is','a','new','col']
df3['abc']=['Yet','another','new','col',np.NaN]
df3

first col  second col  third col  fourth col  fifth col      abc
first row    0.822893   -1.423711   0.418590    0.158221  -0.463175      Yet
second row  -0.152790    0.002065   1.858880   -0.636972  -0.738839  another
third row   -0.193864   -1.179945   0.380241    1.376465   0.184676      new
fourth row   1.131401    0.407221  -2.539193    0.328429  -0.027129      col
fifth row   -0.790992    0.408077  -0.746851    0.895058  -0.923893      NaN

In [ ]:
# we can add columns to a dataframe
df3['sixth col'] = np.random.randn(5,1)
df3

first col  second col  third col  fourth col  fifth col      abc  \
first row    0.822893   -1.423711   0.418590    0.158221  -0.463175      Yet   
second row  -0.152790    0.002065   1.858880   -0.636972  -0.738839  another   
third row   -0.193864   -1.179945   0.380241    1.376465   0.184676      new   
fourth row   1.131401    0.407221  -2.539193    0.328429  -0.027129      col   
fifth row   -0.790992    0.408077  -0.746851    0.895058  -0.923893      NaN   

            sixth col  
first row   -1.440577  
second row   0.281420  
third row   -0.024457  
fourth row   0.873589  
fifth row   -0.268849

In [ ]:
# we can remove columns or rows from a dataframe
# Method 1
df3=df3.drop('third col',axis=1)

In [ ]:
# Method 2
df3.drop('abc',axis=1,inplace=True)

In [ ]:
df3

first col  second col  fourth col  fifth col  sixth col
first row    0.822893   -1.423711    0.158221  -0.463175  -1.440577
second row  -0.152790    0.002065   -0.636972  -0.738839   0.281420
third row   -0.193864   -1.179945    1.376465   0.184676  -0.024457
fourth row   1.131401    0.407221    0.328429  -0.027129   0.873589
fifth row   -0.790992    0.408077    0.895058  -0.923893  -0.268849

In [ ]:
df3.drop('second col',axis=1)

first col  fourth col  fifth col  sixth col
first row    0.822893    0.158221  -0.463175  -1.440577
second row  -0.152790   -0.636972  -0.738839   0.281420
third row   -0.193864    1.376465   0.184676  -0.024457
fourth row   1.131401    0.328429  -0.027129   0.873589
fifth row   -0.790992    0.895058  -0.923893  -0.268849

In [ ]:
df3

first col  second col  fourth col  fifth col  sixth col
first row    0.822893   -1.423711    0.158221  -0.463175  -1.440577
second row  -0.152790    0.002065   -0.636972  -0.738839   0.281420
third row   -0.193864   -1.179945    1.376465   0.184676  -0.024457
fourth row   1.131401    0.407221    0.328429  -0.027129   0.873589
fifth row   -0.790992    0.408077    0.895058  -0.923893  -0.268849

In [ ]:
df4 = df3.drop(['second col'],axis=1)
df4

first col  fourth col  fifth col  sixth col
first row    0.822893    0.158221  -0.463175  -1.440577
second row  -0.152790   -0.636972  -0.738839   0.281420
third row   -0.193864    1.376465   0.184676  -0.024457
fourth row   1.131401    0.328429  -0.027129   0.873589
fifth row   -0.790992    0.895058  -0.923893  -0.268849

In [ ]:
df5 = df3.drop('second row',axis=0)
df5

first col  second col  fourth col  fifth col  sixth col
first row    0.822893   -1.423711    0.158221  -0.463175  -1.440577
third row   -0.193864   -1.179945    1.376465   0.184676  -0.024457
fourth row   1.131401    0.407221    0.328429  -0.027129   0.873589
fifth row   -0.790992    0.408077    0.895058  -0.923893  -0.268849

In [ ]:
df3=df3.drop('second row',axis=0)
df3

first col  second col  fourth col  fifth col  sixth col
first row    0.822893   -1.423711    0.158221  -0.463175  -1.440577
third row   -0.193864   -1.179945    1.376465   0.184676  -0.024457
fourth row   1.131401    0.407221    0.328429  -0.027129   0.873589
fifth row   -0.790992    0.408077    0.895058  -0.923893  -0.268849

In [ ]:
df3.drop('fifth row',axis=0,inplace=True)
df3

first col  second col  fourth col  fifth col  sixth col
first row    0.822893   -1.423711    0.158221  -0.463175  -1.440577
third row   -0.193864   -1.179945    1.376465   0.184676  -0.024457
fourth row   1.131401    0.407221    0.328429  -0.027129   0.873589

In [ ]:
# Pandas - Series, DataFrame


In [ ]:
s=pd.Series([1,2,3,4],index=['a','b','c','d'])

In [ ]:
s[1:3]

b    2
c    3
dtype: int64

In [ ]:
df5.iloc[1:3,1:3]

second col  fourth col
third row    -1.179945    1.376465
fourth row    0.407221    0.328429

In [ ]:
df5

first col  second col  fourth col  fifth col  sixth col
first row    0.822893   -1.423711    0.158221  -0.463175  -1.440577
third row   -0.193864   -1.179945    1.376465   0.184676  -0.024457
fourth row   1.131401    0.407221    0.328429  -0.027129   0.873589
fifth row   -0.790992    0.408077    0.895058  -0.923893  -0.268849

In [ ]:
df5.loc[['fifth row','fourth row'],['first col','fourth col']]

first col  fourth col
fifth row   -0.790992    0.895058
fourth row   1.131401    0.328429

In [ ]:
df5[df5>0]

first col  second col  fourth col  fifth col  sixth col
first row    0.822893         NaN    0.158221        NaN        NaN
third row         NaN         NaN    1.376465   0.184676        NaN
fourth row   1.131401    0.407221    0.328429        NaN   0.873589
fifth row         NaN    0.408077    0.895058        NaN        NaN

In [ ]:
df=pd.DataFrame(np.random.randint(5,35,(5,6)))

In [ ]:
df

0   1   2   3   4   5
0  24   7  17   8  33  29
1  17  31  15  28  27  31
2  24  14  11   8  29  24
3  26  30  20  13  32  19
4  27  31  29   8   5   7

In [ ]:
# - Give me numbers greater than 25
df[(df>25) & (df%2==0)]

0     1   2     3     4   5
0   NaN   NaN NaN   NaN   NaN NaN
1   NaN   NaN NaN  28.0   NaN NaN
2   NaN   NaN NaN   NaN   NaN NaN
3  26.0  30.0 NaN   NaN  32.0 NaN
4   NaN   NaN NaN   NaN   NaN NaN

In [ ]:
df5[(df5>0.5)]

first col  second col  fourth col  fifth col  sixth col
first row    0.822893         NaN         NaN        NaN        NaN
third row         NaN         NaN    1.376465        NaN        NaN
fourth row   1.131401         NaN         NaN        NaN   0.873589
fifth row         NaN         NaN    0.895058        NaN        NaN

In [ ]:
df5.drop('first row',axis=0,inplace=True)

In [ ]:
df5

first col  second col  fourth col  fifth col  sixth col
third row   -0.193864   -1.179945    1.376465   0.184676  -0.024457
fourth row   1.131401    0.407221    0.328429  -0.027129   0.873589
fifth row   -0.790992    0.408077    0.895058  -0.923893  -0.268849

In [ ]:
# we can remove a dataframe's index labels
df5.reset_index(inplace=True)

In [ ]:
df5

index  first col  second col  fourth col  fifth col  sixth col
0   third row  -0.193864   -1.179945    1.376465   0.184676  -0.024457
1  fourth row   1.131401    0.407221    0.328429  -0.027129   0.873589
2   fifth row  -0.790992    0.408077    0.895058  -0.923893  -0.268849

In [ ]:
df5.reset_index(inplace=True)
df5

level_0       index  first col  second col  fourth col  fifth col  \
0        0   third row  -0.193864   -1.179945    1.376465   0.184676   
1        1  fourth row   1.131401    0.407221    0.328429  -0.027129   
2        2   fifth row  -0.790992    0.408077    0.895058  -0.923893   

   sixth col  
0  -0.024457  
1   0.873589  
2  -0.268849

In [ ]:
s=['uno','dos','tres']

In [ ]:
df5['Level_1']=s
df5.set_index('Level_1')

level_0       index  first col  second col  fourth col  fifth col  \
Level_1                                                                      
uno            0   third row  -0.193864   -1.179945    1.376465   0.184676   
dos            1  fourth row   1.131401    0.407221    0.328429  -0.027129   
tres           2   fifth row  -0.790992    0.408077    0.895058  -0.923893   

         sixth col  
Level_1             
uno      -0.024457  
dos       0.873589  
tres     -0.268849

In [ ]:
df5.drop('level_0',axis=1)

index  first col  second col  fourth col  fifth col  sixth col Level_1
0   third row  -0.193864   -1.179945    1.376465   0.184676  -0.024457     uno
1  fourth row   1.131401    0.407221    0.328429  -0.027129   0.873589     dos
2   fifth row  -0.790992    0.408077    0.895058  -0.923893  -0.268849    tres

In [ ]:
df5.set_index('second col')

level_0       index  first col  fourth col  fifth col  sixth col  \
second col                                                                     
-1.179945         0   third row  -0.193864    1.376465   0.184676  -0.024457   
 0.407221         1  fourth row   1.131401    0.328429  -0.027129   0.873589   
 0.408077         2   fifth row  -0.790992    0.895058  -0.923893  -0.268849   

           Level_1  
second col          
-1.179945      uno  
 0.407221      dos  
 0.408077     tres

In [ ]:
# we can assign new names to the index
df5['new index'] = ['This','is a new','row']
df5

ValueError: Length of values (3) does not match length of index (4)

In [ ]:
df5.reset_index()

In [ ]:
df5['Row_index']=['uno','dos','tres','cuanta']
df5.set_index('Row_index')

In [ ]:
df5

In [ ]:
df5.set_index('Row_index',inplace=True)
df5

In [ ]:
df5.reset_index()

ValueError: cannot insert level_0, already exists

## Pandas Lecture 2

# Combining data frames

The ways dataframes are combined in pandas is similar to SQL

We will examine 3 methods for combining dataframes

1. concat
2. join
3. merge

In [ ]:


df7 = pd.DataFrame({"customer":['101','102','103','104'], 
                    'category': ['cat2','cat2','cat1','cat3'],
                    'important': ['yes','no','yes','yes'],
                    'sales': [123,52,214,663]},index=[0,1,2,3])

df8 = pd.DataFrame({"customer":['101','103','104','105'], 
                    'color': ['yellow','green','green','blue'],
                    'distance': [12,9,44,21],
                    'sales': [123,214,663,331]},index=[4,5,6,7])

#list of tuples


In [ ]:
print(df7)
print('')
print(df8)

  customer category important  sales
0      101     cat2       yes    123
1      102     cat2        no     52
2      103     cat1       yes    214
3      104     cat3       yes    663

  customer   color  distance  sales
4      101  yellow        12    123
5      103   green         9    214
6      104   green        44    663
7      105    blue        21    331


In [ ]:
df7

customer category important  sales
0      101     cat2       yes    123
1      102     cat2        no     52
2      103     cat1       yes    214
3      104     cat3       yes    663

In [ ]:
pd.concat([df7,df8],axis=0,sort=False)

customer category important  sales   color  distance
0      101     cat2       yes    123     NaN       NaN
1      102     cat2        no     52     NaN       NaN
2      103     cat1       yes    214     NaN       NaN
3      104     cat3       yes    663     NaN       NaN
4      101      NaN       NaN    123  yellow      12.0
5      103      NaN       NaN    214   green       9.0
6      104      NaN       NaN    663   green      44.0
7      105      NaN       NaN    331    blue      21.0

In [ ]:
pd.concat([df7,df8],axis=1,sort=True)

customer category important  sales customer   color  distance  sales
0      101     cat2       yes  123.0      NaN     NaN       NaN    NaN
1      102     cat2        no   52.0      NaN     NaN       NaN    NaN
2      103     cat1       yes  214.0      NaN     NaN       NaN    NaN
3      104     cat3       yes  663.0      NaN     NaN       NaN    NaN
4      NaN      NaN       NaN    NaN      101  yellow      12.0  123.0
5      NaN      NaN       NaN    NaN      103   green       9.0  214.0
6      NaN      NaN       NaN    NaN      104   green      44.0  663.0
7      NaN      NaN       NaN    NaN      105    blue      21.0  331.0

In [ ]:
pd.concat([df7,df8],axis=1,sort=False)

customer category important  sales customer   color  distance  sales
0      101     cat2       yes  123.0      NaN     NaN       NaN    NaN
1      102     cat2        no   52.0      NaN     NaN       NaN    NaN
2      103     cat1       yes  214.0      NaN     NaN       NaN    NaN
3      104     cat3       yes  663.0      NaN     NaN       NaN    NaN
4      NaN      NaN       NaN    NaN      101  yellow      12.0  123.0
5      NaN      NaN       NaN    NaN      103   green       9.0  214.0
6      NaN      NaN       NaN    NaN      104   green      44.0  663.0
7      NaN      NaN       NaN    NaN      105    blue      21.0  331.0

# Merge and Join

Merge combines dataframes using a column's values to identify common entries

Join combines dataframes using the index to identify common entries

In [ ]:
print(df7)
print('')
print(df8)

  customer category important  sales
0      101     cat2       yes    123
1      102     cat2        no     52
2      103     cat1       yes    214
3      104     cat3       yes    663

  customer   color  distance  sales
4      101  yellow        12    123
5      103   green         9    214
6      104   green        44    663
7      105    blue        21    331


In [ ]:
pd.merge(df7,df8,how='left',on=['customer','sales']) # outer merge is union of on

customer category important  sales   color  distance
0      101     cat2       yes    123  yellow      12.0
1      102     cat2        no     52     NaN       NaN
2      103     cat1       yes    214   green       9.0
3      104     cat3       yes    663   green      44.0

In [ ]:
pd.merge(df7,df8,how='inner',on='customer') # inner merge is intersection of on

customer category important  sales_x   color  distance  sales_y
0      101     cat2       yes      123  yellow        12      123
1      103     cat1       yes      214   green         9      214
2      104     cat3       yes      663   green        44      663

In [ ]:
pd.merge(df7,df8,'right','customer') # left merge is just first on, but all columns ... right is second

customer category important  sales_x   color  distance  sales_y
0      101     cat2       yes    123.0  yellow        12      123
1      103     cat1       yes    214.0   green         9      214
2      104     cat3       yes    663.0   green        44      663
3      105      NaN       NaN      NaN    blue        21      331

In [ ]:
pd.merge(df7,df8,'outer','customer') # left merge is just first on, but all columns ... right is second

customer category important  sales_x   color  distance  sales_y
0      101     cat2       yes    123.0  yellow      12.0    123.0
1      102     cat2        no     52.0     NaN       NaN      NaN
2      103     cat1       yes    214.0   green       9.0    214.0
3      104     cat3       yes    663.0   green      44.0    663.0
4      105      NaN       NaN      NaN    blue      21.0    331.0

In [ ]:
df9 = pd.DataFrame({'Q1': [101,102,103],
                    'Q2': [201,202,203]},
                   index=['I0','I1','I2'])

df10 = pd.DataFrame({'Q3': [301,302,303],
                    'Q4': [401,402,403]},
                   index=['I0','I2','I3'])

In [ ]:
print(df9)
print('')
print(df10)

     Q1   Q2
I0  101  201
I1  102  202
I2  103  203

     Q3   Q4
I0  301  401
I2  302  402
I3  303  403


In [ ]:
# join behaves just like merge, 
# except instead of using the values of one of the columns 
# to combine data frames, it uses the index labels
df9.join(df10,how='left') # outer, inner, left, and right work the same as merge

Q1   Q2     Q3     Q4
I0  101  201  301.0  401.0
I1  102  202    NaN    NaN
I2  103  203  302.0  402.0

In [ ]:
df8['color']
df8.color

4    yellow
5     green
6     green
7      blue
Name: color, dtype: object

In [ ]:
df8.color.nunique()

# - unique - gives all unique values
# - unique() - output - np.array 
# - nunique() - number of unique values - len(df.color.unique())

3

In [ ]:
df8.sales.value_counts()
# output - series

123    1
214    1
663    1
331    1
Name: sales, dtype: int64

In [ ]:
df8.color.value_counts()

green     2
yellow    1
blue      1
Name: color, dtype: int64

In [ ]:
df8['color'].unique()

array(['yellow', 'green', 'blue'], dtype=object)

In [ ]:
# let's now go over a few more basic functialities of pandas

df8['color'].unique()

array(['yellow', 'green', 'blue'], dtype=object)

In [ ]:
df8['color'].value_counts()

green     2
yellow    1
blue      1
Name: color, dtype: int64

In [ ]:
df9

Q1   Q2
I0  101  201
I1  102  202
I2  103  203

In [ ]:
df9.mean(axis=0)

Q1    102.0
Q2    202.0
dtype: float64

In [ ]:
df9.mean(axis=0)

Q1    102.0
Q2    202.0
dtype: float64

In [ ]:
df8.columns

Index(['customer', 'color', 'distance', 'sales'], dtype='object')

In [ ]:
df8['color']

4    yellow
5     green
6     green
7      blue
Name: color, dtype: object

In [ ]:
df8

customer   color  distance  sales
4      101  yellow        12    123
5      103   green         9    214
6      104   green        44    663
7      105    blue        21    331

In [ ]:
# -- rows having color as green
df8[df8.color=='green']

customer  color  distance  sales
5      103  green         9    214
6      104  green        44    663

In [ ]:
# Rows having green and distance even
df8[(df8.color=='green') & (df8.distance%2==0)][['color','distance']]

color  distance
6  green        44

In [ ]:
df[['color','distance']]

color  distance
6  green        44

In [ ]:
df8[(df8['color']=='green') & (df8['distance']<10)]

customer  color  distance  sales
5      103  green         9    214

In [ ]:
df8

customer   color  distance  sales
4      101  yellow        12    123
5      103   green         9    214
6      104   green        44    663
7      105    blue        21    331

In [ ]:
df8[(df8['color']=='green') & (df8.distance<10)]


customer  color  distance  sales
5      103  green         9    214

In [ ]:
df8.sales.mean()

332.75

In [ ]:
print(df8['sales'].sum())
# print(df8['distance'].min()) #
df8.distance.min()


1331


9

In [ ]:
df8

customer   color  distance  sales
4      101  yellow        12    123
5      103   green         9    214
6      104   green        44    663
7      105    blue        21    331

In [ ]:
df8['profit']=df8.sales*0.2

In [ ]:
df8

customer   color  distance  sales  profit
4      101  yellow        12    123    24.6
5      103   green         9    214    42.8
6      104   green        44    663   132.6
7      105    blue        21    331    66.2

In [ ]:
def profit(s):
    return s*20/100

In [ ]:
df8['profit1']=df8.sales.apply(profit)

In [ ]:
df8['discount']=df8.profit.apply(lambda x:x/2)

In [ ]:
df8

customer   color  distance  sales  profit  profit1  discount
4      101  yellow        12    123    24.6     24.6      12.3
5      103   green         9    214    42.8     42.8      21.4
6      104   green        44    663   132.6    132.6      66.3
7      105    blue        21    331    66.2     66.2      33.1

In [ ]:
def profit(s):
    return s*0.5 # 50% markup...

In [ ]:
df8['sales']

4    123
5    214
6    663
7    331
Name: sales, dtype: int64

In [ ]:
df8['sales'].apply(profit)

4     61.5
5    107.0
6    331.5
7    165.5
Name: sales, dtype: float64

In [ ]:
df8['color'].apply(len)

4    6
5    5
6    5
7    4
Name: color, dtype: int64

In [ ]:
df11 = df8[['distance','sales']]
df11.applymap(profit)
# df11

distance  sales
4       6.0   61.5
5       4.5  107.0
6      22.0  331.5
7      10.5  165.5

In [ ]:
df11

distance  sales
4        12    123
5         9    214
6        44    663
7        21    331

In [ ]:
def col_sum(abc):
    return sum(abc)
df11.apply(col_sum)

distance      86
sales       1331
dtype: int64

In [ ]:
del df11

In [ ]:
df11

NameError: name 'df11' is not defined

In [ ]:
del df8['color']
df8

customer  distance  sales
4      101        12    123
5      103         9    214
6      104        44    663
7      105        21    331

In [ ]:
df8.columns

Index(['customer', 'distance', 'sales'], dtype='object')

In [ ]:
df8.index

Int64Index([4, 5, 6, 7], dtype='int64')

In [ ]:
df8.sort_values(by=['sales'],ascending=False,inplace=True)
df8

customer  distance  sales
6      104        44    663
7      105        21    331
5      103         9    214
4      101        12    123

In [ ]:
df8

customer  distance  sales
6      104        44    663
7      105        21    331
5      103         9    214
4      101        12    123

In [ ]:
# if some series has multiple of the same value then we can group all the unique entries together
mydict = {'customer': ['Customer 1','Customer 1','Customer2','Customer2','Customer3','Customer3'], 
          'product1': [1.1,2.1,3.8,4.2,5.5,6.9],
          'product2': [8.2,9.1,11.1,5.2,44.66,983]}
df6 = pd.DataFrame(mydict,index=['Purchase 1','Purchase 2','Purchase 3','Purchase 4','Purchase 5','Purchase 6'])
df6

customer  product1  product2
Purchase 1  Customer 1       1.1      8.20
Purchase 2  Customer 1       2.1      9.10
Purchase 3   Customer2       3.8     11.10
Purchase 4   Customer2       4.2      5.20
Purchase 5   Customer3       5.5     44.66
Purchase 6   Customer3       6.9    983.00

In [ ]:
df6.groupby('customer').mean()


product1  product2
customer                      
Customer 1       1.6      8.65
Customer2        4.0      8.15
Customer3        6.2    513.83

In [ ]:
df8

## Working with a CSV File

In [ ]:
import pandas as pd
df = pd.read_csv("weather_data.csv")   #read weather.csv data
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [ ]:
#list of tuples

weather_data = [('1/1/2017', 32, 6, 'Rain'),
                ('1/2/2017', 35, 7, 'Sunny'),
                ('1/3/2017', 28, 2, 'Snow'),
                ('1/4/2017', 24, 7, 'Snow'),
                ('1/5/2017', 32, 4, 'Rain'),
                ('1/6/2017', 31, 2, 'Sunny')
               ]
df = pd.DataFrame(weather_data, columns=['day', 'temperature', 'windspeed', 'event'])
df

day  temp  windspeed  event
0  1/1/2017    32          6   Rain
1  1/2/2017    35          7  Sunny
2  1/3/2017    28          2   Snow
3  1/4/2017    24          7   Snow
4  1/5/2017    32          4   Rain
5  1/6/2017    31          2  Sunny

In [ ]:
#get dimentions of the table

df.shape   #total number of rows and columns

(6, 4)

In [ ]:
df.head(2)

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny

In [ ]:
df.tail(4)

day  temperature  windspeed  event
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [ ]:
df.describe()

temperature  windspeed
count     6.000000   6.000000
mean     30.333333   4.666667
std       3.829708   2.338090
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.500000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

In [ ]:
#if you want to see initial some rows then use head command (default 5 rows)
df.head()

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain

In [ ]:
#if you want to see last few rows then use tail command (default last 5 rows will print)
df.tail()

day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [ ]:
#slicing
df[2:5]

day  temperature  windspeed event
2  1/3/2017           28          2  Snow
3  1/4/2017           24          7  Snow
4  1/5/2017           32          4  Rain

In [ ]:
df.columns   #print columns in a table

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [ ]:
df.day      #print particular column data

df['day']


0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/6/2017
Name: day, dtype: object

In [ ]:
#another way of accessing column
df['day'] #df.day (both are same)

0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/6/2017
Name: day, dtype: object

In [ ]:
#get 2 or more columns
df[['day', 'event']]

day  event
0  1/1/2017   Rain
1  1/2/2017  Sunny
2  1/3/2017   Snow
3  1/4/2017   Snow
4  1/5/2017   Rain
5  1/6/2017  Sunny

In [ ]:
# row with min temp
df[df.temperature==df.temperature.min()]

day  temperature  windspeed event
3  1/4/2017           24          7  Snow

In [ ]:
#get all temperatures
df['temperature']

0    32
1    35
2    28
3    24
4    32
5    31
Name: temperature, dtype: int64

In [ ]:
#print max temperature
df['temperature'].max()

35

In [ ]:
#print max temperature
df['temperature'].min()

24

In [ ]:
#print max temperature
df['temperature'].describe()

count     6.000000
mean     30.333333
std       3.829708
min      24.000000
25%      28.750000
50%      31.500000
75%      32.000000
max      35.000000
Name: temperature, dtype: float64

In [ ]:
# select rows which has maximum temperature
df[df.temperature == df.temperature.max()] 


day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny

In [ ]:
#select only day column which has maximum temperature
df[df.temperature == df.temperature.max()][['day','event']]


day  event
1  1/2/2017  Sunny