In [ ]:
import pandas as pd
import numpy as np

In [ ]:
l1= [1,2,3,4]

In [ ]:
a= pd.Series(l1)
a

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
l2= np.random.randint(10,20,4)
l2

array([12, 12, 19, 10])

In [ ]:
b=pd.Series(l2)
b

0    12
1    12
2    19
3    10
dtype: int64

In [ ]:
mylabels= ['a', 'b', 'c', 'd']

In [ ]:
b= pd.Series(data= l2, index= mylabels)
b

a    12
b    12
c    19
d    10
dtype: int64

In [ ]:
b= pd.Series(l2, mylabels)
b

a    12
b    12
c    19
d    10
dtype: int64

In [ ]:
b['c':]

c    19
d    10
dtype: int64

In [ ]:
l3= [2, 3, 5, 6]

In [ ]:
c= pd.Series(l3, ['b', 'e', 'c', 'f'])
c

b    2
e    3
c    5
f    6
dtype: int64

In [ ]:
b

a    12
b    12
c    19
d    10
dtype: int64

In [ ]:
c

b    2
e    3
c    5
f    6
dtype: int64

In [ ]:
b+c

a     NaN
b    14.0
c    24.0
d     NaN
e     NaN
f     NaN
dtype: float64

In [ ]:
e= pd.concat([b, c], axis=0, sort= False)
e   # Not a Dataframe

a    12
b    12
c    19
d    10
b     2
e     3
c     5
f     6
dtype: int64

In [ ]:
d= pd.concat([b, c], axis=1, sort= False)
d

0    1
a  12.0  NaN
b  12.0  2.0
c  19.0  5.0
d  10.0  NaN
e   NaN  3.0
f   NaN  6.0

In [ ]:
f= pd.DataFrame(np.random.rand(4, 5), index=['a', 'b', 'c', 'd'], columns=['p', 'q', 'r', 's', 't'])
f

p         q         r         s         t
a  0.725253  0.602369  0.238691  0.528966  0.742582
b  0.384574  0.067042  0.438843  0.513776  0.803900
c  0.947233  0.086560  0.102163  0.770414  0.279095
d  0.236327  0.996958  0.020669  0.540307  0.041334

In [ ]:
f[f['p']>0.5][['p']]=2

/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py:3645: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[col] = value


In [ ]:
f.loc[f['p']>0.5, 'p']=5

In [ ]:
f

p         q         r         s         t
a  5.000000  0.602369  0.238691  0.528966  0.742582
b  0.384574  0.067042  0.438843  0.513776  0.803900
c  5.000000  0.086560  0.102163  0.770414  0.279095
d  0.236327  0.996958  0.020669  0.540307  0.041334

In [ ]:
h= np.arange(1,10).reshape(3,3)
h

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
h[1]

array([4, 5, 6])

In [ ]:
h[1:, [1,2]]

array([[5, 6],
       [8, 9]])

In [ ]:
f[['q', 'r']]

q         r
a  0.099274  0.897620
b  0.360040  0.642104
c  0.637840  0.432038
d  0.786164  0.490341

In [ ]:
f.loc[['b','c','d'],['p', 'q']] # loc - for normal loc row and coumns

p         q
b  0.884334  0.360040
c  0.261786  0.637840
d  0.760617  0.786164

In [ ]:
f.iloc[1:4, 0:2]  # iloc - for index loc

p         q
b  0.884334  0.360040
c  0.261786  0.637840
d  0.760617  0.786164

In [ ]:
lon = [6,26,46,71,0,2,5,6,61,3,2,5,6,7,2,6,7,3,7,9,6,7,2,6,2]

In [ ]:
b= list(map(lambda x: x*2, lon))

In [ ]:
for i in range(len(lon)-1):
  if lon[i]==0:
    continue
  elif lon[i] %2==0:
    lon[i+1]=lon[i+1]+1
  else:
    lon[i+1]=lon[i+1]+0
print(lon)

[6, 27, 46, 72, 1, 2, 6, 7, 61, 3, 2, 6, 7, 7, 2, 7, 7, 3, 7, 9, 6, 8, 3, 6, 3]
